language: python

sudo: false

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7

install:
  - pip install -U coverage coveralls


script: coverage run --source=torrentool/ tests/runtests.py


after_success:
  coveralls
