language: python

sudo: false

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7

install:
  - pip install pytest coverage coveralls

script:
  - coverage run --source=torrentool setup.py test

after_success:
  - coveralls
